name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: b703f4a8-acf5-445b-b5b1-d10867ae1150 #${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "drops-apply" #Must be unique in Heroku
          heroku_email: "francisco170142329@gmail.com"